### ISSUE TITLE
unresolved import `syn::export`

### ISSUE THREAD

**Issue by ajosecueto** [NyxCode/ormx#9]
Hello i want to use ormx = "0.2.0" because I'm working with sql 0.4 and actix and I can't update still to 0.5.

I'm getting this error from macros...

error[E0432]: unresolved import `syn::export`
 --> /Users/macbookpro/.cargo/registry/src/github.com-1ecc6299db9ec823/ormx-macros-0.1.8/src/backend/common/table.rs:3:10
  |
3 | use syn::export::TokenStreamExt;
  |          ^^^^^^ could not find `export` in `syn`

I'm using Rust 1.50

thanks for your help...

**Comment by NyxCode** [comment]
Oh, yeah, that's something I hadn't thought about. I will publish a fix for 0.2 soon. Sorry for your inconvinience.

**Comment by ajosecueto** [comment]
Thanks, for now I edit that file and change to use quote::TokenStreamExt and works.

**Comment by NyxCode** [comment]
ormx 0.2 is *very* outdated now, so I would like to stop supporting it. I hope you can somehow use sqlx 0.5 now.
